Allow missing documentation in all of src/util.rs
To avoid the following error:

error: missing documentation for a function [-D missing-docs]
  --> src/util.rs:11:1
   |
11 | ioctl!(read blkgetsize64 with 0x12, 114; u64);
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in a macro outside of the current crate

error: aborting due to previous error

Signed-off-by: mulhern <amulhern@redhat.com>